steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/geth-exporter:$COMMIT_SHA', '.' ]
   waitFor: ["-"]
 images:
 - 'gcr.io/$PROJECT_ID/geth-exporter:$COMMIT_SHA'
